### PR TITLE
Support for final release of v16

### PR DESCRIPTION
**Pull request by amertak**
Drop support for beta and rc versions of 16 in favor of final release.
Both stable v15 and v16 still working.

### CODE REVIEW

**Comment by amertak** [comment]
One thing to point out is that with v16 this library is kinda not necessary ;)

**Comment by pradel** [comment]
Hey, could you also change the peer dependencies in `package.json` please?
Yeah you are right 😄

**Comment by amertak** [comment]
Done :)

**Comment by amertak** [comment]
There is also react in devDep but that's up to you if you want to move it to newer version since v16 is obsole.

**Comment by pradel** [comment]
Thank you!

**Pull request merged**
